export type { Rng, RngState } from './rng.js'
export { createRng, rngFromState, seedState } from './rng.js'
export { T as tunables, applyOverrides } from './tunables.js'
export type { Tunables } from './tunables.js'
export type * from './types.js'
export { emit } from './events.js'
export { createWorld, gravityTarget } from './world/gen.js'
export { digestWorld, fnv1a } from './digest.js'
export { bandIndex, clubBandIndex, isElite, tiersForReputation } from './managers/reputation.js'
export { advanceWeek, runSeasons, runWeeks } from './sim/advance.js'
export { advanceTurn, humanClubId, nextSlot, humanHasFixtureIn, commitWatched, discardWatched, prepareWatchedSlot, findFixture, fixtureKey } from './sim/turn.js'
export type { TurnOptions, Slot } from './sim/turn.js'
export { nextFixture, seasonFixtures } from './play/fixtures.js'
export type { NextFixture, FixtureView, CompetitionFixtures } from './play/fixtures.js'
export { seasonOf, seasonWeek } from './season/calendar.js'
export { matchOdds, playMatch, plainBands, shootoutHomeChance } from './season/match.js'
export type { Participant, MatchOdds, MatchOutcome } from './season/match.js'
export { prepareFixture, settleFixture, createFixtureMatch, commitFixtureMatch, lineupFor } from './season/season.js'
export type { PreparedFixture, FixtureResult, FixtureFacts, PlayedFixture, Lineup } from './season/season.js'
export { analyticGoals, pressureLean, chanceProfile, goalChance, sideRating } from './match/model.js'
export type { SideView } from './match/model.js'
export { fastOdds, calibratedGoals, jointPmf, sampleScoreline, FAST_PATH_TABLE } from './match/fastpath.js'
export type { FastPathTable, FastOdds } from './match/fastpath.js'
export { FORMATIONS, FORMATION_NAMES, slotsOf, structureOf } from './players/formations.js'
export { TRAITS, TRAIT_RULES, hasTrait } from './players/traits.js'
export { autoPick, enforceSelection, effectiveRating, positionPenalty, xiBands, bestXiMean, squadOf, available, clubFormation } from './players/select.js'
export { generateSquad, anchorSquad, wageFor, valueFor, positionMix, makePlayer } from './players/gen.js'
export { wageDemand, wantsNewDeal, wantsAway } from './players/contracts.js'
export { tagPlayer, tagOf, tagWeight, growWithMinutes, developmentFactor, playersMadeFromLog, madePlayers } from './players/made.js'
export type { MadePlayerSummary } from './players/made.js'
export { averageRating, attributeGoals, cardChance, injuryChance, matchRating, applyFacts, oneShotFacts } from './match/aftermath.js'
export type { SideFacts, PlayerFacts, SideStats, Scorer, SideInput } from './match/aftermath.js'
export { createMatch, tick, runToEnd, substitute, setMentality, bestReplacement, factsOf, liveBands, sideView, pressureTarget, scoreline } from './match/minute.js'
export type { MatchState, MatchSide, MatchPlayer, MatchEvent, EventKind, SideSetup } from './match/minute.js'
export { tableFor, positionOf } from './season/table.js'
export { renderMatch } from './text/render.js'
export { clubById, homeClub, managerById, spellById, spellOf, managerAt, europeanOpponentById, anyClubName, playerById } from './lookup.js'
export { startSpell, endSpell, activeSpells, salaryFor, contractEndWeek } from './tenure/spell.js'
export { expectationAtHire, structuralTarget } from './tenure/expectation.js'
export { openVacancies } from './market/vacancies.js'
export { agentFit, agentPick, applicationInFlight } from './market/agent.js'
export { qualifies, wouldApply, poachable, agePenalty } from './market/shortlist.js'
export { reviewTags, assignTag, hasTag } from './market/tags.js'
export { endCareer } from './market/retirement.js'
export { careerScore, legacy, trophyPointsFor, promotionPointsFrom } from './scoring/score.js'
export { runCareers } from './sim/run.js'
export type { RunOptions, RunResult } from './sim/run.js'
export { populationStats, countLongTopTierTenures, trackedManagers, median } from './stats/population.js'
export type { PopulationStats, StatLine, Histogram } from './stats/population.js'
export { createCareer, careerSummary } from './play/career.js'
export type { CareerOptions, CareerSummary, SpellSummary, Gambles } from './play/career.js'
export { pendingDecisions } from './play/decisions.js'
export { confidenceFor, selectionWords, rollOutcome } from './play/bets.js'
export { windowState, windowAt, scoutedView, wageBill, needs, estimateSd, rangeHalf } from './market/director.js'
export type { WindowState, WindowName, Candidate, SaleProposal } from './market/director.js'
export { requestOptions, requestLikelihood, searchPlayers, shortlistRows, wordsFor } from './play/requests.js'
export type { RequestOffer, Likelihood, SearchFilter, SearchRow } from './play/requests.js'
export { inbox, inboxSince, inboxMark, competitionName, competitionLabel } from './play/inbox.js'
export type { InboxItem, InboxFrom, InboxMark } from './play/inbox.js'
export { boardMood } from './tenure/hooks.js'
export { renderText, ordinal, clubNameOf } from './text/render.js'
