export type { Rng, RngState } from './rng.js'
export { createRng, rngFromState, seedState } from './rng.js'
export { T as tunables, applyOverrides } from './tunables.js'
export type { Tunables } from './tunables.js'
export type * from './types.js'
export { emit } from './events.js'
export { createWorld, gravityTarget } from './world/gen.js'
export { digestWorld, fnv1a } from './digest.js'
export { bandIndex, clubBandIndex, foreignBandIndex, isElite, tiersForReputation } from './managers/reputation.js'
export { advanceWeek, runSeasons, runWeeks } from './sim/advance.js'
export { seasonOf, seasonWeek } from './season/calendar.js'
export { matchOdds, playMatch } from './season/match.js'
export { tableFor, positionOf } from './season/table.js'
export { renderMatch } from './text/render.js'
export { clubById, homeClub, managerById, spellById, spellOf, managerAt } from './lookup.js'
export { startSpell, endSpell, activeSpells, salaryFor, contractEndWeek } from './tenure/spell.js'
export { expectationAtHire, structuralTarget } from './tenure/expectation.js'
export { openVacancies } from './market/vacancies.js'
export { qualifies, wouldApply, poachable, agePenalty } from './market/shortlist.js'
export { reviewTags, assignTag, hasTag } from './market/tags.js'
export { endCareer } from './market/retirement.js'
export { careerScore, legacy, trophyPointsFor, promotionPointsFrom } from './scoring/score.js'
export { runCareers } from './sim/run.js'
export type { RunOptions, RunResult } from './sim/run.js'
export { populationStats, countLongTopTierTenures, trackedManagers, median } from './stats/population.js'
export type { PopulationStats, StatLine, Histogram } from './stats/population.js'
export { createCareer, careerSummary } from './play/career.js'
export type { CareerOptions, CareerSummary, SpellSummary } from './play/career.js'
export { pendingDecisions } from './play/decisions.js'
export { inbox, competitionName } from './play/inbox.js'
export type { InboxItem, InboxFrom } from './play/inbox.js'
export { boardMood } from './tenure/hooks.js'
export { renderText } from './text/render.js'
